### ISSUE TITLE
4.0.0 jar and source archives are unopenable

### ISSUE THREAD

**Issue by jeffmc930** [Unicon/shib-cas-authn#2]
The files for the 4.0.0 release files aren't openable by any zip tool. I get the following error for example:

jar -tf shib-cas-authenticator-4.0.0.jar
java.util.zip.ZipException: zip END header not found

The .zip and tgz source files have unknown format errors when trying to open them.

What am I missing?

I grabbed the master copy and built it, so I'm fine.

**Comment by pspaude** [comment]
I'm able to download and open the files with standard archive tools and the jar command is successful along with `zip -t` on the zip. 

I'd start with making sure your Java version is 11 or greater. That should fix the jar command. If you're already at that version and it still doesn't work, then it's likely either an OS issue (perhaps try 7zip if on Windows) or an security appliance/extension is corrupting the downloads.

**Comment by pspaude** [comment]
I'm going to close this as the jars have been updated since, and others have been able to access them. Please continue to let us know if you encounter any further issues by opening a new issue.
